# Generated by Django 2.2.3 on 2019-07-12 09:49

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_author_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(on_delete=builtins.id, to='store.Author'),
        ),
    ]
